### ISSUE TITLE
Comment for bash in code block

### ISSUE THREAD

**Issue by BercziSandor** [gwenzek/sublime_markdeep#1]
The comment (# CommentText ) in a code block should not formatted like other section text, it is not a section.

Example:
![image](https://cloud.githubusercontent.com/assets/1443421/24800143/26262540-1b9f-11e7-8b47-cf51acf36f2a.png)

**Comment by gwenzek** [comment]
Thanks for reporting.
I didn't even know I had [users](https://packagecontrol.io/packages/Markdeep) !

The problem was that for some reason I was forcing code block to have at least 4 tildes/backquotes.
So your code block wasn't properly recognized.

I changed it to 3, which is the normal value.
As a thank you I added a "bash" support for code block.

If you type
```
# section
~~~ sh
# comment
~~~
```

Then "# comment" should appear as a comment.

The package should update automatically within 48 hours (assuming you are using Package Control).
Please tell me if it solved the problem.
